name: Generate Interop Report

on:
  workflow_dispatch:
  push:
  schedule:
    # update the integration suite once per week at Sunday 5am UTC
    - cron: '0 5 * * 0'

jobs:
  lint:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --legacy-peer-deps
    - name: Run eslint
      run: npm run lint
  test-node:
    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npm dependencies
        run: npm install --legacy-peer-deps
      - name: Run test with Node.js ${{ matrix.node-version }}
        env:
          CLIENT_SECRET_DB: ${{ secrets.CLIENT_SECRET_DB }}
        run: npm run test
        continue-on-error: true
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: reports
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Report Github Pages Deployment Status
        run: echo $deployment_status
